# Generated by Django 5.1.4 on 2024-12-24 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_assigned_nurses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='assigned_nurses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'nurse'}, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
