# Generated by Django 5.1.4 on 2024-12-24 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_age_alter_patient_date_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_nurses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'nurse'}, null=True, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
