# Generated by Django 5.1.4 on 2024-12-22 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('occupied', 'occupied'), ('maintenance', 'maintenance')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='CheckUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('bp', models.CharField(blank=True, max_length=20, null=True)),
                ('pr', models.CharField(blank=True, max_length=20, null=True)),
                ('rr', models.CharField(blank=True, max_length=20, null=True)),
                ('t', models.CharField(blank=True, max_length=20, null=True)),
                ('input', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='core.case')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
