# Generated by Django 5.1.4 on 2024-12-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bed_status_checkup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='treatment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
