# Generated by Django 5.1.4 on 2024-12-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immunization',
            old_name='Treatment',
            new_name='treatment',
        ),
        migrations.RenameField(
            model_name='labresult',
            old_name='Treatment',
            new_name='treatment',
        ),
    ]
