# Generated by Django 5.1.4 on 2024-12-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_bed_asigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bed',
        ),
    ]
