### Login Test
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
  "username": "nurse3",
  "password": "password"
}

### 

### Logout Test
POST http://127.0.0.1:8000/api/logout/
Content-Type: application/json
Authorization: Token 8f1f0abc079a82869eb09391ee6b3a71b94cae8f




### Patient list View (patients assigned to the nurse)
GET http://127.0.0.1:8000/api/patients/
Content-Type: application/json
Authorization: Token 8f1f0abc079a82869eb09391ee6b3a71b94cae8f
// the token is from the login response 




### Active Case for patient View  -- id is the id of the patient
GET http://127.0.0.1:8000/api/patient/6/case/
Content-Type: application/json
Authorization: Token 8f1f0abc079a82869eb09391ee6b3a71b94cae8f

### checkups for specific case --id is the id of the case
GET http://127.0.0.1:8000/api/case/16/checkups/
Content-Type: application/json
Authorization: Token 8f1f0abc079a82869eb09391ee6b3a71b94cae8f

###
GET http://127.0.0.1:8000/api/bed/3/
Content-Type: application/json
Authorization: Token 8f1f0abc079a82869eb09391ee6b3a71b94cae8f


### adding the new checkup for the specific case -- id is the id of the case
POST http://127.0.0.1:8000/api/case/16/add-checkup/
Content-Type: application/json
Authorization: Token 8f1f0abc079a82869eb09391ee6b3a71b94cae8f

{
    "bp": "120/80",
    "pr": "72",
    "rr": "18",
    "t": "98.6",
    "input": "Oral intake 500ml",
    "output": "Urine output 300ml",
    "additional_information": "Patient is stable"
}



