# Generated by Django 5.1.4 on 2024-12-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_treatment_treatment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('doctor', 'doctor'), ('nurse', 'nurse')], default='nurse', max_length=10),
        ),
    ]
